/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nz_ac_canterbury_ling_praat_SendPraat */

#ifndef _Included_nzilbb_jsendpraat_SendPraat
#define _Included_nzilbb_jsendpraat_SendPraat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nzilbb_jsendpraat_SendPraat
 * Method:    sendpraat
 * Signature: (Ljava/lang/String;JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nzilbb_jsendpraat_SendPraat_sendpraatNative
  (JNIEnv *, jobject, jstring, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
